- name: chromedriver
  block:
    # to prevent dpkg lock errors.
    - name: wait for apt
      shell: |
        while pgrep -x apt >/dev/null; do sleep 5; done;
      register: my_output # <- Registers the command output.
      changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Install prerequisites
      apt:
        pkg:
          - curl
          - unzip
          - xvfb
          - libxi6
          - libgconf-2-4
          - default-jdk

    - name: Add Google Chrome apt signing key
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub

    - name: Add Google Chrome repository to sources
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

    - name: Install google-chrome-stable
      apt:
        name: google-chrome-stable
        update_cache: true

    - name: Get Chrome Version Number
      shell: google-chrome --version | awk '{print $3}'
      register: chromedriver_version_number
      changed_when: false

    - name: Download chromedriver {{ chromedriver_version_number.stdout }}
      unarchive:
        src: https://storage.googleapis.com/chrome-for-testing-public/{{ chromedriver_version_number.stdout }}/linux64/chromedriver-linux64.zip
        dest: /root/
        group: root
        owner: root
        remote_src: true
        mode: u+x,g+x,o+x

    - name: Move chromedriver bin into /usr/bin
      copy:
        src: /root/chromedriver-linux64/chromedriver
        dest: /usr/bin
        group: root
        owner: root
        remote_src: true
        mode: u+x,g+x,o+x

    - name: Create chrome user account
      user:
        name: chrome

    - name: Add chromedriver.service to /etc/systemd/system/chromedriver.service
      copy:
        src: chromedriver.service
        dest: /etc/systemd/system/chromedriver.service
        group: root
        owner: root
        mode: 0644

    - name: Stop chromedriver service
      systemd:
        name: chromedriver
        state: stopped

    - name: Enable chromedriver service
      systemd:
        name: chromedriver
        enabled: true

    - name: Start chromedriver service
      systemd:
        name: chromedriver
        state: started
  become: true
