- name: grafana_loki
  block:
    - name: Check for Loki {{ loki_architecture }}/{{ loki_version }}
      stat:
        path: ~/loki-{{ loki_architecture }}
      register: loki

    - name: Download Loki {{ loki_architecture }}/{{ loki_version }}
      unarchive:
        src: https://github.com/grafana/loki/releases/download/{{ loki_version }}/loki-{{ loki_architecture }}.zip
        dest: /root
        remote_src: true
      when: not loki.stat.exists

    - name: Add loki-config config to /root/loki-config.yaml
      template:
        src: loki-config.yaml.j2
        dest: /root/loki-config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Add loki.service file to /etc/systemd/system/loki_systemd.service
      template:
        src: loki_systemd.service.j2
        dest: /etc/systemd/system/loki.service
        owner: root
        group: root
        mode: 0644

    - name: Enable loki service
      systemd:
        name: loki
        enabled: true

    - name: Stop loki service
      systemd:
        name: loki
        state: stopped
      when: ansible_facts.services[loki_systemd] is not defined

    - name: Start loki service
      systemd:
        daemon_reload: true
        name: loki
        state: started

  become: true
