- name: setup_node
  environment:
    AWS_CONFIG_FILE: /home/admin/.aws/credentials
  block:
    - name: Populate service facts
      service_facts:

    - name: Find AWS file for {{ app_name }} in S3 {% if target_release_sha | length > 0 %} with sha {{ target_release_sha }} {% else %} latest {% endif %} and set it into variable
      ansible.builtin.script:
        cmd: >
          {% if target_release_sha | length > 0 %}
            find_aws_release_by_sha.sh {{ bucket_name }} {{ app_name }} "{{ release_prefix }}" {{ target_release_sha }}
          {% else %}
            latest_aws_release.sh {{ bucket_name }} {{ app_name }} "{{ release_prefix }}"
          {% endif %}
      register: aws_file_name

    - name: Set local release path
      set_fact:
        s3_object_key: "{{ aws_file_name.stdout_lines[0] }}"
        local_release_file: "{{ app_name }}/{{ aws_file_name.stdout_lines[0] | basename }}"

    - name: Create {{ app_name }} srv directory
      file:
        path: /srv/{{ app_name }}
        state: directory

    - name: Download {{ app_name }} from S3
      amazon.aws.aws_s3:
        bucket: "{{ bucket_name }}"
        mode: get
        object: "{{ s3_object_key }}"
        dest: /srv/{{ local_release_file }}

    - name: Create /srv/{{ app_name }} directory
      file:
        path: /srv/{{ app_name }}
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create /srv/unpack-directory directory
      file:
        path: /srv/unpack-directory
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Untar {{ local_release_file }}
      unarchive:
        src: /srv/{{ local_release_file }}
        dest: /srv/unpack-directory
        remote_src: true

    - name: Update release state for {{ app_name }}
      ansible.builtin.script:
        cmd: update_release_state.sh {{ bucket_name }} {{ release_state_prefix }} {{ app_name }} {{ s3_object_key }}
      register: release_state_result
      changed_when: "'changed' in release_state_result.stdout"

    - name: Add erlang_systemd.service file to /etc/systemd/system/{{ app_name }}.service
      template:
        src: erlang_systemd.service.j2
        dest: /etc/systemd/system/{{ app_name }}.service
        owner: root
        group: root
        mode: 0644
      # when: app_name == item
      # loop: "{{ erlang_systemd }}"

    - name: Add environment varaibles to systemd.service file
      lineinfile:
        path: /etc/systemd/system/{{ app_name }}.service
        insertafter: RestartSec=5
        line: "Environment=\"{{ item }}\""
      loop: "{{ system_env }}"

    - name: Enable {{ app_name }} service
      systemd:
        name: "{{ app_name }}"
        enabled: true

    - name: Stop {{ app_name }} service
      systemd:
        name: "{{ app_name }}"
        state: stopped
      when: ansible_facts.services[ app_name ] is not defined

    - name: Delete old /srv/{{ app_name }} directory
      file:
        path: /srv/{{ app_name }}
        state: absent

    - name: Copy /srv/unpack-directory directory to /srv/{{ app_name }}
      copy:
        src: /srv/unpack-directory/
        dest: /srv/{{ app_name }}/
        mode: 0755
        remote_src: true

    - name: Delete /srv/unpack-directory directory
      file:
        path: /srv/unpack-directory
        state: absent

    - name: Start {{ app_name }} service with {{ local_release_file }}
      systemd:
        daemon_reload: true
        name: "{{ app_name }}"
        state: started

  become: true
