- name: pip3
  block:
    - name: Check if pip3 is installed
      stat:
        path: /usr/bin/pip3
      register: pip3_python

    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: true
      when: (not pip3_python.stat.exists)

    - name: Install setuptools
      pip:
        name: setuptools
        executable: pip3
  become: true
