- name: ipv6
  block:
    - name: Create ipv6 config file
      ansible.builtin.copy:
        content: export AWS_USE_DUALSTACK_ENDPOINT=true
        dest: /etc/profile.d/aws-ipv6.sh
        owner: root
        group: root
        mode: '0644'

    - name: Add dualstack to boto config
      ansible.builtin.copy:
        content: |
          [profile default]
          s3_use_dualstack_endpoint = true
        dest: ~/.aws/config
        owner: root
        group: root
        mode: '0644'

  become: true
