- name: grafana_loki_promtail
  block:
    - name: Check for Prom Tail {{ promtail_architecture }}/{{ promtail_version }}
      stat:
        path: ~/promtail-{{ promtail_architecture }}
      register: promtail

    - name: Download Promtail {{ promtail_architecture }}/{{ promtail_version }}
      unarchive:
        src: https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-{{ promtail_architecture }}.zip
        dest: /root
        remote_src: true
      when: not promtail.stat.exists

    - name: Add Promtail config to /root/promtail_config.yaml
      template:
        src: promtail_config.yaml.j2
        dest: /root/promtail_config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Add promtail_systemd.service file to /etc/systemd/system/promtail.service
      template:
        src: promtail_systemd.service.j2
        dest: /etc/systemd/system/promtail.service
        owner: root
        group: root
        mode: 0644

    - name: Enable promtail service
      systemd:
        name: promtail
        enabled: true

    - name: Stop promtail service
      systemd:
        name: promtail
        state: stopped
      when: ansible_facts.services[promtail] is not defined

    - name: Start promtail service
      systemd:
        daemon_reload: true
        name: promtail
        state: started


  become: true
