- name: prometheus_db
  block:
    - name: Install Prometheus DB
      apt:
        name: prometheus
        policy_rc_d: 101
        update_cache: true

    - name: Add PrometheusDB config to /root/prometheus.yaml
      template:
        src: prometheus.yaml.j2
        dest: /root/prometheus-config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Stop prometheus original service
      systemd:
        name: prometheus
        state: stopped

    - name: Disable the original prometheus service
      systemd:
        name: prometheus
        enabled: no

    - name: Delete prometheus original service
      ansible.builtin.file:
        state: absent
        path: /lib/systemd/system/prometheus.service

    - name: Add prometheus.service file to /etc/systemd/system/prometheus.service
      template:
        src: prometheus_db.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: 0644

    - name: Enable prometheus service
      systemd:
        name: prometheus
        enabled: true

    - name: Stop prometheus service
      systemd:
        name: prometheus
        state: stopped
      when: ansible_facts.services[prometheus] is not defined

    - name: Start prometheus service
      systemd:
        daemon_reload: true
        name: prometheus
        state: started

  become: true


