- name: prometheus_db
  block:
    - name: Install Prometheus DB
      apt:
        name: prometheus
        update_cache: true

    - name: Add PrometheusDB config to /root/prometheus.yaml
      template:
        src: prometheus.yaml.j2
        dest: /root/prometheus_config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Add prometheus_scraper.service file to /etc/systemd/system/prometheus_scraper.service
      template:
        src: prometheus_scraper.service.j2
        dest: /etc/systemd/system/prometheus_scraper.service
        owner: root
        group: root
        mode: 0644

    - name: Enable prometheus_scraper service
      systemd:
        name: prometheus_scraper
        enabled: true

    - name: Stop prometheus_scraper service
      systemd:
        name: prometheus_scraper
        state: stopped
      when: ansible_facts.services[prometheus_scraper] is not defined

    - name: Start prometheus_scraper service
      systemd:
        daemon_reload: true
        name: prometheus_scraper
        state: started

  become: true

