- name: prometheus_db
  block:
    - name: Install Prometheus DB
      apt:
        name: prometheus
        update_cache: true

    - name: Add PrometheusDB config to /root/prometheus.yaml
      template:
        src: prometheus.yaml.j2
        dest: /root/prometheus-config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Stop prometheus original service
      systemd:
        name: prometheus
        state: stopped

    - name: Add prometheus_scraper.service file to /etc/systemd/system/prometheus_scraper.service
      template:
        src: prometheus_db.service.j2
        dest: /etc/systemd/system/prometheus_db.service
        owner: root
        group: root
        mode: 0644

    - name: Enable prometheus_db service
      systemd:
        name: prometheus_db
        enabled: true

    - name: Stop prometheus_db service
      systemd:
        name: prometheus_db
        state: stopped
      when: ansible_facts.services[prometheus_db] is not defined

    - name: Start prometheus_db service
      systemd:
        daemon_reload: true
        name: prometheus_db
        state: started

  become: true

