- name: prometheus_exporter
  block:
    - name: Install prometheus-node-exporter
      apt:
        name: prometheus-node-exporter
        update_cache: true
      register: prometheus_exporter

    - name: Enable prom-node-exporter service
      systemd:
        enabled: true
        name: prometheus-node-exporter
      when: prometheus_exporter.changed

    - name: Stop promtail service
      systemd:
        name: promtail
        state: stopped
      when: prometheus_exporter.changed and ansible_facts.services[promtail] is not defined

    - name: Start promtail service
      systemd:
        daemon_reload: true
        name: promtail
        state: started
      when: prometheus_exporter.changed
  become: true

