- name: prometheus_exporter
  block:
    - name: Install prometheus-node-exporter
      apt:
        name: prometheus-node-exporter
        update_cache: true
      register: prometheus_exporter

    - name: Enable prom-node-exporter service
      systemd:
        daemon_reload: true
        state: started
        name: prometheus_exporter
      when: prometheus_exporter.changed

    - name: Restart prom-node-exporter service
      systemd:
        state: restarted
        name: prometheus_exporter
      when: prometheus_exporter.changed
  become: true

