- name: oci_cli
  block:
    - name: Check if oci cli is installed
      stat:
        path: /usr/local/bin/oci
      register: oci_cli_exe

    - name: Check if oci cli is updated to {{ oci_cli_version }}
      command: oci --version
      register: oci_cli_current_version
      when: oci_cli_exe.stat.exists
      changed_when: false

    - name: Install jq (required to parse oci CLI JSON output)
      apt:
        name: jq
        update_cache: true

    - name: Install oci-cli {{ oci_cli_version }}
      pip:
        name: "oci-cli=={{ oci_cli_version }}"
        executable: pip3
        extra_args: --break-system-packages
      when: (not oci_cli_exe.stat.exists) or (oci_cli_current_version.stdout != oci_cli_version)

  become: true
